### ISSUE TITLE
Logs files too huge

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/particle-agent#5]
```
My Particle-Pi has been failing, during my digging I found a 1.2Gb log file.
```

See:  http://community.particle.io/t/massive-log-file/30143

**Comment by Legend2015** [comment]
Have the same issue, i couldn't start the GUI, then did some digging found the particle-agent.log is 21GB!!! (I am running my Pi3 from a 32GB USB flash drive)

**Comment by darkwinternight** [comment]
Also deleting the file causes it to not be recreated.

**Comment by abbott** [comment]
Same issue. Device was not booting properly. Storage full from 6.1GB log file.
